status: live
title: AI SkillForge
pitch: An AI-native learning platform where Gemini AI generates personalized, interactive learning experiences for mastering prompt engineering and Google AI tools.
category: education
platform: lovable
featured: false
live_url: https://skillforge-ai-coach.lovable.app
cover_image: src/assets/hero-banner.jpg
cover_prompt: A sleek learning dashboard with glowing AI neural network connections, interactive curriculum cards, and a friendly AI coach avatar guiding a learner through personalized skill paths.
tags:
  - ai
  - education
  - gemini
  - prompt-engineering
  - learning
