// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxggzyqsojtvnxcrcspm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4Z2d6eXFzb2p0dm54Y3Jjc3BtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MDU2MjUsImV4cCI6MjA2ODM4MTYyNX0.0fFDtC7e2Ub_dm6dkxS3p22RzPZxRQQBeNLJ-GunKEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});